name: summons-svc Image Build workflow
on:
  pull_request:
    types:
      - closed
    branches:
      - develop
    paths:
      - 'backend/summons-svc/**'
  workflow_dispatch:
  workflow_call:

jobs:
  docker_image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        run: docker login -u pucarsolutionsdev -p ${{ secrets.ACR_PASSWORD }} pucarsolutionsdev.azurecr.io

      - name: Get Merge commit of PR
        run: |
          PR_NUMBER=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" | jq -r '.[0].number')
          Merge_Commit=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" | jq -r '.merge_commit_sha')
          echo "Merge_Commit=$Merge_Commit" >> $GITHUB_ENV

      - name: Build and Push Docker image for summons-svc
        run: |
          docker build --build-arg WORK_DIR="backend/summons-svc" -t pucarsolutionsdev.azurecr.io/summons-svc:v1.0.0-${{ env.Merge_Commit }} -f build/maven/Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/summons-svc:v1.0.0-${{ env.Merge_Commit }}

      - name: Build and Push Docker image for summons-svc_DB
        run: |
          docker build  -t pucarsolutionsdev.azurecr.io/summons-svc_db:v1.0.0-${{ env.Merge_Commit }} -f  Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/summons-svc_db:v1.0.0-${{ env.Merge_Commit }}
        working-directory: backend/summons-svc/src/main/resources/db

  Workflow_Trigger:
    runs-on: ubuntu-latest
    needs: docker_image-build
    steps:
      - name: Trigger Deployment Pipeline for Solutions Dev
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GHUB_TOKEN }}" \
          https://api.github.com/repos/pucardotorg/pucar-Devops/actions/workflows/solutions-dev.yaml/dispatches \
          -d '{"ref":"Solutions-Pipeline"}'
